"""startup

Revision ID: 19f653dfed1a
Revises: edbca3c9aef1
Create Date: 2022-02-04 11:36:36.053456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f653dfed1a'
down_revision = 'edbca3c9aef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.SmallInteger(), nullable=False),
    sa.Column('press', sa.SmallInteger(), nullable=False),
    sa.Column('humid', sa.SmallInteger(), nullable=False),
    sa.Column('wind_speed', sa.SmallInteger(), nullable=False),
    sa.Column('wind_direction', sa.SmallInteger(), nullable=False),
    sa.Column('event_direction', sa.SmallInteger(), nullable=False),
    sa.Column('bno_direction', sa.SmallInteger(), nullable=False),
    sa.Column('current', sa.SmallInteger(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('power', sa.SmallInteger(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['weather_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('weather_data')
    op.drop_table('users')
    # ### end Alembic commands ###
