"""build out database

Revision ID: edbca3c9aef1
Revises: 5f9f1b6f8ba7
Create Date: 2022-02-04 07:04:59.313590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbca3c9aef1'
down_revision = '5f9f1b6f8ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['weather_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('weather_data', sa.Column('press', sa.SmallInteger(), nullable=False))
    op.add_column('weather_data', sa.Column('humid', sa.SmallInteger(), nullable=False))
    op.add_column('weather_data', sa.Column('wind_speed', sa.SmallInteger(), nullable=False))
    op.add_column('weather_data', sa.Column('wind_direction', sa.SmallInteger(), nullable=False))
    #op.add_column('weather_data', sa.Column('event_direction', sa.SmallInteger(), nullable=False))
    op.add_column('weather_data', sa.Column('bno_direction', sa.SmallInteger(), nullable=False))
    op.add_column('weather_data', sa.Column('current', sa.SmallInteger(), nullable=False))
    op.add_column('weather_data', sa.Column('voltage', sa.Float(), nullable=False))
    op.add_column('weather_data', sa.Column('power', sa.SmallInteger(), nullable=False))
#    op.add_column('weather_data', sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('weather_data', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_data', 'created_at')
    op.drop_column('weather_data', 'date')
    op.drop_column('weather_data', 'power')
    op.drop_column('weather_data', 'voltage')
    op.drop_column('weather_data', 'current')
    op.drop_column('weather_data', 'bno_direction')
    #op.drop_column('weather_data', 'event_direction')
    op.drop_column('weather_data', 'wind_direction')
    op.drop_column('weather_data', 'wind_speed')
    op.drop_column('weather_data', 'humid')
    op.drop_column('weather_data', 'press')
    op.drop_table('votes')
    op.drop_table('users')
    # ### end Alembic commands ###
